# Do not read host's /etc/resolv.conf
no-resolv

# (Optional) Upstream DNS servers for non-wildcard lookups
server=8.8.8.8
server=8.8.4.4

# Wildcard: resolve ALL domains to 192.168.1.100
address=/.cbadger.dedyn.io/192.168.23.156

# (Optional) log queries to stdout
log-queries
log-facility=-
