---
services:
  caddy:
    image: caddy:2.10.0-builder
    # image: "caddy-reverse-certify:latest"
    # build:
    #   context: . # build from current directory
    #   dockerfile: Dockerfile # use this dockerfile
    #   args:
    #     - BUILD_DATE=${BUILD_DATE}
    #     - VCS_REF=${VCS_REF}
    #     - VERSION=${VERSION}
    volumes:
      - ./caddy-data:/data # certificates / state
      - ./boot.sh:/usr/bin/boot:ro
      - ./app.py:/usr/bin/app:ro
      - ./templates.py:/usr/bin/templates.py:ro
      - ./status.py:/usr/bin/status.py:ro
      - ./config.yml:/config.yml:ro
    ports:
      - "80:80"
      - "443:443"
    entrypoint: ["/usr/bin/boot"]
    restart: unless-stopped
  dnsmasq:
    image: andyshinn/dnsmasq:latest # lightweight dnsmasq image
    container_name: dnsmasq
    ports:
      - "53:53/udp" # DNS over UDP
      - "53:53/tcp" # DNS over TCP
    volumes:
      - ./caddy-data/dnsmasq.conf:/etc/dnsmasq.conf:ro # mount config from /data
    restart: unless-stopped
    depends_on:
      - caddy
